version: "3"

services:
  qslbureau-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_TCP_PORT: ${MYSQL_PORT}
    ports:
      - "${MYSQL_PORT}"
    volumes:
      - ./opt/mysql:/var/lib/mysql
    restart: always
    networks:
      - network-backend
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 30s
      timeout: 5s
      retries: 5

  qslbureau-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - qslbureau-db
    environment:
      PMA_HOST: qslbureau-db
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${PHPMYADMIN_EXTERNAL_PORT}:80
    networks:
      - network-backend
    depends_on:
      qslbureau-db:
        condition: service_healthy

  qslbureau-recibir-back:
    image: "${DOCKER_USER_NAME}/qslbureau-back:${DOCKER_ENVIRONMENT}"
    ports:
      - "8080:8080"
    depends_on:
      qslbureau-db:
        condition: service_healthy
    environment:
      MYSQL_DB_URL: jdbc:mysql://qslbureau-db:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8&&enabledTLSProtocols=TLSv1.2
      MYSQL_DB_USERNAME: ${MYSQL_USER}
      MYSQL_DB_PASSWORD: ${MYSQL_PASSWORD}
      ROOT_LOG_LEVEL: ${ROOT_LOG_LEVEL}
      FRONT_NAMESERVER: "http://localhost:${FRONT_EXTERNAL_PORT}"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - network-backend
    healthcheck:
      test: curl -m 5 --silent --fail --request GET http://localhost:8080/actuator/health | jq --exit-status -n 'inputs | if has("status") then .status=="UP" else false end' > /dev/null || exit 1
      interval: 30s
      timeout: 5s
      retries: 5

  qslbureau-recibir-front:
    image: "${DOCKER_USER_NAME}/qslbureau-front:${DOCKER_ENVIRONMENT}"
    ports:
      - "${FRONT_EXTERNAL_PORT}:80"
    depends_on:
      qslbureau-recibir-back:
        condition: service_healthy
    environment:
      API_URL: http://qslbureau-recibir-back:8080
    networks:
      - network-backend
    restart: on-failure:3
    
networks:
  network-backend:
